version: "3"
services:
  omdb-mysql:
    image: mysql:8.2
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
        - omdb
  omdb:
    image: omdb
    build: .
    ports:
      - "5555:8000"
    depends_on:
      omdb-mysql:
        condition: service_healthy
    environment:
      - ENVIRONMENT=production
      - SERVICE_DATABASE_USER=root
      - SERVICE_DATABASE_PASSWORD=1234
      - SERVICE_DATABASE_HOST=omdb-mysql
      - SERVICE_DATABASE_PORT=3306
    networks:
        - omdb
networks:
  omdb:
    driver: bridge
volumes:
  mysql_data:
